nines_util:
    trim_length: 50
    routing:
        - { class: App\Entity\Document, route: document_show }
        - { class: App\Entity\DocumentSet, route: document_set_show }
        - { class: App\Entity\Compilation, route: compilation_show }
