nines_user:
    resource: '@NinesUserBundle/Resources/config/routes.yaml'

nines_dc:
    type: annotation
    prefix: /dc
    resource: '@NinesDublinCoreBundle/Controller'

nines_editor:
    type: annotation
    prefix: /editor
    resource: '@NinesEditorBundle/Controller'

nines_media:
    type: annotation
    prefix: /media
    resource: '@NinesMediaBundle/Controller'
